name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
          cache: true
      - name: Build
        run: |
          go build -o apple-music-downloader.exe -v .
      - name: Create distribution
        run: |
          mkdir -p alac
          copy agent.js alac\
          copy agent-arm64.js alac\
          copy config.yaml.example alac\config.yaml
          copy README.md alac\
          copy apple-music-downloader.exe alac\
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apple-music-alac-atmos-downloader-windows
          path: alac

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
          cache: true
      - name: Build
        run: |
          go build -o apple-music-downloader -v .
      - name: Create distribution
        run: |
          mkdir -p alac
          cp agent.js alac/
          cp agent-arm64.js alac/
          cp config.yaml.example alac/config.yaml
          cp README.md alac/
          cp apple-music-downloader alac/
          chmod +x alac/apple-music-downloader
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apple-music-alac-atmos-downloader-linux
          path: alac

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
          cache: true
      - name: Build
        run: |
          go build -o apple-music-downloader -v .
      - name: Create distribution
        run: |
          mkdir -p alac
          cp agent.js alac/
          cp agent-arm64.js alac/
          cp config.yaml.example alac/config.yaml
          cp README.md alac/
          cp apple-music-downloader alac/
          chmod +x alac/apple-music-downloader
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apple-music-alac-atmos-downloader-macos
          path: alac